# JVM args for the Gradle daemon.
org.gradle.jvmargs=-Xmx3g -XX:+UseParallelGC -Dfile.encoding=UTF-8
# Build speed
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
# Smaller, faster R classes: each module gets only its own resources.
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
